services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    container_name: blog-nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: blog-postgres-db
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_nextjs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
